include: package:very_good_analysis/analysis_options.yaml
analyzer:
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
    - '**/*.config.dart'
    - '**/*.gen.dart'
    - '**/feature**/*_test.dart'
  errors:
    avoid_positional_boolean_parameters: ignore
    cascade_invocations: ignore
    duplicate_ignore: ignore
    inference_failure_on_function_invocation: ignore
    library_private_types_in_public_api: ignore
    public_member_api_docs: ignore
    require_trailing_commas: ignore
    type_annotate_public_apis: ignore
    unnecessary_raw_strings: ignore
