include: package:very_good_analysis/analysis_options.yaml
analyzer:
  errors:
    avoid_positional_boolean_parameters: ignore
    duplicate_ignore: ignore
    library_private_types_in_public_api: ignore
    public_member_api_docs: ignore
    require_trailing_commas: ignore
    unnecessary_raw_strings: ignore
