name: meno_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  cached_network_image: ^3.4.1
  dartz: ^0.10.1
  dio: ^5.8.0+1
  envied: ^1.1.1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.2
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.5
  flutter_riverpod: ^2.6.1
  flutter_secure_storage: ^9.2.4
  flutter_web_plugins:
    sdk: flutter
  formz: ^0.8.0
  go_router: ^14.8.1
  hooks_riverpod: ^2.6.1
  image_picker: ^1.1.2
  intl: ^0.20.2
  json_annotation: ^4.9.0
  jwt_decoder: ^2.0.1
  meno_design_system:
    path: ../meno_design_system
  meta: ^1.16.0
  readmore: ^3.0.0
  responsive_framework: ^1.5.1
  retrofit: ^4.4.2
  riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  rxdart: ^0.28.0
  shared_preferences: ^2.5.3
  skeletonizer: ^1.4.3
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.4.15
  custom_lint: ^0.7.5
  envied_generator: ^1.1.1
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  go_router_builder: ^2.3.0
  json_serializable: ^6.9.4
  mockito: ^5.4.5
  retrofit_generator: ^9.1.9
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5
  test: ^1.25.15
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/splash-logo.png
    
  fonts:
    - family: MIcons
      fonts:
        - asset: fonts/MIcons.ttf
        - asset: fonts/MIcons.main.ttf

flutter_native_splash:
  color: "#260066"
  image: assets/splash-logo.png
  icon_background_color: "#260066"

  android_12:
    color: "#260066"
    image: assets/splash-logo.png
    icon_background_color: "#260066"